version: '3.3'
services:
    linuxserver:
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
            #- TRANSMISSION_WEB_HOME=/combustion-release/
        ports:
            - '9091:9091'
            - '51413:51413'
            - '51413:51413/udp'
        volumes:
            - '/mnt/containerconfig/transmission/config:/config'
            - '/mnt/public/torrents:/downloads'
            - '/mnt/public:/media'
            - '/mnt/public/torrents/autoget:/watch'
            - '/mnt/local-lvm-slow:/local-lvm-slow'
        restart: unless-stopped
        image: 'lscr.io/linuxserver/transmission:latest'
