version: '3.3'
services:
    linuxserver:
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
        ports:
            - '7878:7878'
        volumes:
            - '/mnt/containerconfig/radarr/config:/config'
            #- '/mnt/public/movies:/movies'
            #- '/mnt/public:/media'
            - '/mnt/plexMedia:/media'
            #- '/mnt/public/movies_spicy:/movies_spicy'
            #- '/mnt/public/torrents:/downloads'
        restart: unless-stopped
        image: 'lscr.io/linuxserver/radarr:latest'
