---
version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /mnt/containerstore/lidarr/config:/config
      - /mnt/public/music:/music
      - /mnt/public/torrents:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
