---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - PEERPORT=51412
    volumes:
      - /mnt/containerconfig/baydownloader/config:/config
      - /mnt/torrents/baydownloads:/downloads
      - /mnt/torrents/baydownloads/autoget:/watch
      - /mnt/local-lvm-slow:/local-lvm-slow
    ports:
      - 9091:9091
      - 51412:51412
      - 51412:51412/udp
    restart: unless-stopped
